server:
  port: 8081

spring:
  application:
    name: server-auth
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: ${keycloak.auth-server-url}/realms/${keycloak.realm}

keycloak:
  auth-server-url: http://localhost:8080
  realm: sandbox-realm
  resource: server-auth-client
  token-uri: ${keycloak.auth-server-url}/realms/${keycloak.realm}/protocol/openid-connect/token
