spring:
  docker:
    compose:
      stop:
        command: down
  sql:
    init:
      mode: always
  ssl:
    bundle:
          jks:                     # ← для PKCS12 / JKS используем jks-группу
            server:                # ← имя бандла (можно любое, но часто берут "server")
              key:
                alias: localhost   # ← должен совпадать с -alias в keytool
              keystore:
                location: classpath:keystore.p12
                password: changeit
                type: PKCS12       # ← обязательно указывать для .p12
              # key-password: changeit   # ← если пароль на ключ отличается от store-пароля
jwt:
  cookie-token-key: '{"kty":"oct","k":"956PBFst1FguLr5irJD-aQ"}'

server:
  ssl:
    bundle: server           # ← имя бандла из предыдущего блока
    port: 8443

logging:
  level:
    org.springframework.security: trace