spring:
  docker:
    compose:
      stop:
        command: down
  ssl:
    bundle:
      jks: # ← для PKCS12 / JKS используем jks-группу
        server: # ← имя бандла (можно любое, но часто берут "server")
          key:
            alias: localhost   # ← должен совпадать с -alias в keytool
          keystore:
            location: classpath:keystore.p12
            password: changeit
            type: PKCS12       # ← обязательно указывать для .p12
          # key-password: changeit   # ← если пароль на ключ отличается от store-пароля

  sql:
    init:
      mode: always
jwt:
  access-token-key: '{"kty":"oct","k":"hi7S5RX5ZRZooHA0RKGctZ-KtR9FoESgCnH-3BNg5XI"}'
  refresh-token-key: '{"kty":"oct","k":"956PBFst1FguLr5irJD-aQ"}'
server:
  http2:
    enabled: true
  port: 8443
  ssl:
    enabled: true
    bundle: "server"  # ← указываем имя SSL bundle
logging:
  level:
    org.springframework.security: trace